# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('token', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contact_id', models.BigIntegerField(default=0)),
                ('contact_key', models.CharField(default='0', max_length=1024)),
                ('display_name', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('NAME', 'Name'), ('PHONE', 'Phone Number'), ('EMAIL', 'Email Address'), ('WHATSAPP', 'Whatsapp ID')], max_length=32)),
                ('value', models.CharField(max_length=1024)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='api.Contact')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='friends',
            field=models.ManyToManyField(related_name='friends', to='api.Contact'),
        ),
        migrations.AddField(
            model_name='client',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Contact'),
        ),
    ]
