# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-03-10 12:56
from __future__ import unicode_literals

import api.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('number', models.TextField(default='000 000 00 00')),
                ('whatsapp', models.TextField(default='0')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='api.Contact'),
        ),
        migrations.AddField(
            model_name='client',
            name='links',
            field=models.ManyToManyField(related_name='links', to='api.Contact'),
        ),
    ]
