# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-03-10 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='info',
        ),
        migrations.RemoveField(
            model_name='client',
            name='links',
        ),
        migrations.AddField(
            model_name='contact',
            name='contacts',
            field=models.ManyToManyField(related_name='links', to='api.Contact'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
