# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170324_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='display_name',
            field=models.CharField(max_length=1024),
        ),
    ]
