# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 13:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_sync'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sync',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
