# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 11:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170324_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rounds_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move', models.CharField(choices=[('RO', 'Rock'), ('PA', 'Paper'), ('SC', 'Scissors'), ('LI', 'Lizard'), ('SP', 'Spock')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='api.Game')),
                ('winner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.Player')),
            ],
        ),
        migrations.RenameField(
            model_name='client',
            old_name='friends',
            new_name='contacts',
        ),
        migrations.AddField(
            model_name='player',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Client'),
        ),
        migrations.AddField(
            model_name='player',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Game'),
        ),
        migrations.AddField(
            model_name='move',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Player'),
        ),
        migrations.AddField(
            model_name='move',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Round'),
        ),
    ]
