# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-03-10 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170310_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='whatsapp_id',
            field=models.CharField(default='0', max_length=512),
        ),
    ]
