# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20170427_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='number',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='round',
            unique_together=set([('game', 'number')]),
        ),
    ]
