# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20170427_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='number',
            field=models.SmallIntegerField(default=0),
        ),
    ]
