# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 13:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20170427_1253'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='move',
            unique_together=set([('round', 'player')]),
        ),
    ]
