# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20170427_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='move',
            field=models.CharField(choices=[('ROC', 'Rock'), ('PAP', 'Paper'), ('SIS', 'Scissors'), ('LIZ', 'Lizard'), ('SPO', 'Spock')], max_length=3),
        ),
    ]
