# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20170427_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='move',
            field=models.CharField(choices=[('ROC', 'Rock'), ('PAP', 'Paper'), ('LIZ', 'Lizard'), ('SPO', 'Spock'), ('SIS', 'Scissors')], max_length=3),
        ),
    ]
