# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20170428_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_won', to='api.Player'),
        ),
        migrations.AlterField(
            model_name='move',
            name='move',
            field=models.CharField(choices=[('PAP', 'Paper'), ('ROC', 'Rock'), ('LIZ', 'Lizard'), ('SPO', 'Spock'), ('SIS', 'Scissors')], max_length=3),
        ),
        migrations.AlterField(
            model_name='round',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rounds_won', to='api.Player'),
        ),
    ]
