# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-19 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20170510_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='secret',
            field=models.TextField(default='00'),
        ),
    ]
