# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-20 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20170620_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='energy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Energy'),
        ),
        migrations.AlterField(
            model_name='move',
            name='move',
            field=models.CharField(choices=[('SIS', 'Scissors'), ('LIZ', 'Lizard'), ('SPO', 'Spock'), ('ROC', 'Rock'), ('PAP', 'Paper')], max_length=3),
        ),
    ]
