# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-21 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20170620_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='move',
            name='move',
            field=models.CharField(choices=[('SPO', 'Spock'), ('LIZ', 'Lizard'), ('PAP', 'Paper'), ('ROC', 'Rock'), ('SIS', 'Scissors')], max_length=3),
        ),
    ]
