# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-23 11:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20170622_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='energy',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Energy'),
        ),
        migrations.AlterField(
            model_name='move',
            name='move',
            field=models.CharField(choices=[('SPO', 'Spock'), ('LIZ', 'Lizard'), ('SIS', 'Scissors'), ('ROC', 'Rock'), ('PAP', 'Paper')], max_length=3),
        ),
    ]
