# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-28 08:27
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20170623_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(auto_now_add=True)),
                ('title_args', django.contrib.postgres.fields.jsonb.JSONField(default=[])),
                ('body_args', django.contrib.postgres.fields.jsonb.JSONField(default=[])),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.Client')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('title_key', models.CharField(max_length=256)),
                ('body_key', models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='move',
            name='move',
            field=models.CharField(choices=[('PAP', 'Paper'), ('SIS', 'Scissors'), ('ROC', 'Rock'), ('LIZ', 'Lizard'), ('SPO', 'Spock')], max_length=3),
        ),
        migrations.AddField(
            model_name='notification',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.NotificationTemplate'),
        ),
    ]
