# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-28 11:58
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20170628_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='move',
            field=models.CharField(choices=[('LIZ', 'Lizard'), ('SPO', 'Spock'), ('SIS', 'Scissors'), ('ROC', 'Rock'), ('PAP', 'Paper')], max_length=3),
        ),
        migrations.AlterField(
            model_name='notification',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
