# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-28 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20170628_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='move',
            field=models.CharField(choices=[('LIZ', 'Lizard'), ('SPO', 'Spock'), ('SIS', 'Scissors'), ('ROC', 'Rock'), ('PAP', 'Paper')], max_length=3),
        ),
    ]
